### ISSUE TITLE
Javascript error when attempting to run codegen

### ISSUE THREAD

**Issue by raunak-newsperform** [apollographql/apollo-ios#1732]
**Build is failing with the following outcome,**

```
[DEBUG - ApolloCodegenLib:CLIDownloader.swift:43] - Zip file with the CLI is already downloaded!
SHASUM of downloaded file: d8ff4cd914708479317354721dee8b156acebddb79abbdcda4348a341ab6e53d
[DEBUG - ApolloCodegenLib:CLIExtractor.swift:57] - Binary already extracted!
[ERROR - ApolloCodegenLib:Basher.swift:62] - internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'ansi-styles'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/raunak/Desktop/ApolloClientGreyhounds/Sources/.ApolloCLI/apollo/node_modules/wrap-ansi/index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

Program ended with exit code: 1
```

**Versions**
apollo-ios SDK version: 0.34.1
Xcode version: 12.4
Swift version: 5
Package manager: SPM

**Comment by raunak-newsperform** [comment]
apollo-ios SDK version: 0.34.1
Xcode version: 12.4
Swift version: 5
Package manager: SPM

**Comment by designatednerd** [comment]
Hello! That's quite odd - the binary should include everything necessary from node to run. I would recommend deleting your local copy of the Apollo Typescript CLI (and the zip which contained it) to force a re-download.

**Comment by AnthonyMDev** [comment]
@raunak-newsperform Any update on this, did you solve this issue?

**Comment by raunak-newsperform** [comment]
Thanks guys yes i was able to solve the issue by deleting the local copy of the typescript CLI.
But that wasn't the root cause of the issue, it was the proxy set on my work wifi that was causing the issue.

Thanks again.

**Comment by AnthonyMDev** [comment]
I've been there with the proxy issue. 🤦  Glad this was resolved!
