### ISSUE TITLE
Codegen error migrating from v0.9.0 to v0.9.3

### ISSUE THREAD

**Issue by ChrisBGriffith** [apollographql/apollo-ios#371]
I'm in the process of updating the Apollo iOS client from 0.9.0 -> 0.9.3. This incorporates the new CLI script. I have the proper version of the apollo package installed, but these queries and schema that worked fine with 0.9.0 are failing now. 

```
Apollo Codegen Step
++ npx --no-install apollo codegen:generate '--queries=./GraphQL/CompanyLoginInfo.graphql
./GraphQL/User.graphql
./GraphQL/CompanyDetails.graphql
./GraphQL/SigninUser.graphql' '--schema= GraphQL/schema.json' GraphQL/GraphAPI.swift
[?25l[16:02:22] Loading Apollo config [started]
[16:02:22] Loading Apollo config [completed]
[16:02:22] Resolving GraphQL document sets and dependencies [started]
[16:02:22] Scanning for GraphQL queries (4 found) [title changed]
[16:02:22] Scanning for GraphQL queries (4 found) [completed]
[16:02:22] Generating query files [started]
[16:02:22] Generating query files with 'swift' target [title changed]
[16:02:22] Generating query files with 'swift' target [failed]
[16:02:22] → Cannot read property 'getQueryType' of undefined
[?25hTypeError: Cannot read property 'getQueryType' of undefined
    at TypeInfo.enter (/usr/local/lib/node_modules/apollo/node_modules/graphql/utilities/TypeInfo.js:142:25)
    at Object.enter (/usr/local/lib/node_modules/apollo/node_modules/graphql/language/visitor.js:363:16)
    at Object.visit (/usr/local/lib/node_modules/apollo/node_modules/graphql/language/visitor.js:254:26)
    at getValidationErrors (/usr/local/lib/node_modules/apollo/lib/validation.js:21:15)
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/lib/validation.js:26:30)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:19:18)
    at Task.task (/usr/local/lib/node_modules/apollo/lib/commands/codegen/generate.js:98:64)
    at Promise.resolve.then.then.skipped (/usr/local/lib/node_modules/apollo/node_modules/listr/lib/task.js:167:30)
    at <anonymous>
[?25h
```

**Comment by rodchencko** [comment]
Hi, same problem here since I updated my version of Apollo. It appears to be broken.

**Comment by rodchencko** [comment]
> Glad to know I'm not the only one. :)

Just to let you know that I had to switch back to 0.9. Now it's working again.

**Comment by ChrisBGriffith** [comment]
Yeah, I reverted as well. Everything works in 0.9 - I just like to keep my dependencies updated and it makes me wary when updates break...

**Comment by victormihaita** [comment]
Could you share the the build phase for generating the API.swift?

**Comment by ChrisBGriffith** [comment]
Sure thing, Victor. Below:
```
echo "Apollo Codegen Step"

APOLLO_FRAMEWORK_PATH=$(eval find "$FRAMEWORK_SEARCH_PATHS" -name "Apollo.framework" -maxdepth 1)

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

apollo-codegen download-schema "https://api.${BASE_API_URL}/graphql" --output "./YouEarnedIt/GraphQL/schema.json"

cd "${SRCROOT}/YouEarnedIt"
"$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh" generate $(find . -name '*.graphql') --schema GraphQL/schema.json --output GraphQL/GraphAPI.swift;
```

**Comment by victormihaita** [comment]
You should update to the latest version of Apollo (POD and CLI) and change this in your code:

`cd "${SRCROOT}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-cli.sh codegen:generate GraphQL/GraphAPI.swift --queries="$(find . -name '*.graphql')"  --schema=GraphQL/schema.json`

if you have custom scalars add this: `--passthroughCustomScalars`

**Comment by ChrisBGriffith** [comment]
Ah, my bad. I reverted the code to get it working again with 0.9.0 and copy/pasted it in without thinking. I’ll pull up my stash and past in what I was using for 0.9.3. Sorry for the mixup.

**Comment by ChrisBGriffith** [comment]
@victormihaita I recreated my build script and adding `--passthroughCustomScalars` worked like a champ. Thanks so much!

**Comment by victormihaita** [comment]
I’m happy to hear that! :)

**Comment by ayaseeri** [comment]
I solve this problem by update npm  and  node  to the latest version

**Comment by sivakumaraketi** [comment]
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift
I am using this but gives error Error: No operations or fragments found to generate code for.
    at write (~/node_modules/apollo/lib/commands/client/codegen.js:61:39)
    at Task.task (~/node_modules/apollo/lib/commands/client/codegen.js:86:46)
Command PhaseScriptExecution failed with a nonzero exit code

any help please

**Comment by designatednerd** [comment]
@sivakumaraketi Can you please take a look at the [troubleshooting guide](https://www.apollographql.com/docs/ios/installation/#troubleshooting)? 

If that doesn't help, please open a new issue which includes what version of the Apollo iOS library you're using. The steps to help figure things out are going to be pretty different for older versions like this vs. current versions, and I'd like to disambiguate where errors are happening
