### ISSUE TITLE
schema:download issue, failure saving schema.json

### ISSUE THREAD

**Issue by tsaarva** [apollographql/apollo-ios#389]
I can't seem to download the schema.json in my build...

I’m doing the following before codegen:generate:

$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-cli.sh schema:download --endpoint=$GRAPHQL_ENDPOINT --header=“Authorization: Bearer <token>”

Showing Recent Messages
: [?25l[17:28:41] Loading Apollo config [started]
: [17:28:41] Loading Apollo config [completed]
: [17:28:41] Fetching current schema [started]
: [17:28:41] Fetching current schema [completed]
: [17:28:41] Saving schema to schema.json [started]
: [17:28:41] Saving schema to schema.json [failed]
: [17:28:41] → Expected undefined to be a GraphQL schema.
: [?25hError: Expected undefined to be a GraphQL schema.
:     at invariant (~/myproject/node_modules/graphql/jsutils/invariant.js:19:11)
:     at validateSchema (~/myproject/node_modules/graphql/type/validate.js:55:60)
:     at assertValidSchema (~/myproject/node_modules/graphql/type/validate.js:80:16)
:     at assertValidExecutionArguments (~/myproject/node_modules/graphql/execution/execute.js:201:35)
:     at executeImpl (~/myproject/node_modules/graphql/execution/execute.js:136:3)
:     at Object.execute (~/myproject/node_modules/graphql/execution/execute.js:131:229)
:     at Task.task (~/myproject/node_modules/apollo/lib/commands/schema/download.js:31:113)
:     at Promise.resolve.then.then.skipped (~/myproject/node_modules/listr/lib/task.js:167:30)

**Comment by tsaarva** [comment]
token was expired...
