### ISSUE TITLE
EISDIR error when running Buildscript to generate API.swift

### ISSUE THREAD

**Issue by benleiken** [apollographql/apollo-ios#426]
I'm unable to get the buildscript to run successfully. Using Node 8.1.4, latest Xcode, latest MacOs, npm 6.4.1, and npx 10.2.0. Any idea what the underlying issue could be? I'm at a loss.

`++ npx --no-install apollo codegen:generate --queries= --schema=schema.json API.swift
 ›   Warning: apollo update available from 1.9.2 to 2.1.8
[15:04:51] Loading Apollo config [started]
[15:04:51] Loading Apollo config [completed]
[15:04:51] Resolving GraphQL document sets and dependencies [started]
[15:05:10] Scanning for GraphQL queries (208177 found) [title changed]
[15:05:10] Scanning for GraphQL queries (208177 found) [completed]
[15:05:10] Generating query files [started]
[15:05:10] Generating query files with 'swift' target [title changed]
[15:05:11] Generating query files with 'swift' target [failed]
[15:05:11] → EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at inputPaths.map.inputPath (~/.nvm/versions/node/v8.0.0/lib/node_modules/apollo/node_modules/apollo-codegen-core/lib/loading.js:87:35)
    at loadQueryDocuments (~/.nvm/versions/node/v8.0.0/lib/node_modules/apollo/node_modules/apollo-codegen-core/lib/loading.js:83:10)
    at Object.loadAndMergeQueryDocuments (~/.nvm/versions/node/v8.0.0/lib/node_modules/apollo/node_modules/apollo-codegen-core/lib/loading.js:138:32)
    at Object.generate [as default] (~/.nvm/versions/node/v8.0.0/lib/node_modules/apollo/lib/generate.js:18:32)
    at Task.task (~/.nvm/versions/node/v8.0.0/lib/node_modules/apollo/lib/commands/codegen/generate.js:98:64)
    at Promise.resolve.then.then.skipped (~/.nvm/versions/node/v8.0.0/lib/node_modules/apollo/node_modules/listr/lib/task.js:167:30)
Command PhaseScriptExecution failed with a nonzero exit code`

**Comment by jxltom** [comment]
@benleiken Hey, I just have the same issue, do you know what happend? Many thanks!

**Comment by benleiken** [comment]
@jxltom yeah that was my issue too! error was a bit cryptic!
