### ISSUE TITLE
Error: No operations or fragments found to generate code for

### ISSUE THREAD

**Issue by aamir-nazir** [apollographql/apollo-ios#765]
When I add query in existing `.graphql` file it generates following error, however creating new `.graphql` not updating `API.swift` file and project is being compiled successfully. Apollo won't complain even if I use wrong query name in newly generated `.graphql`.

```Now using node v10.16.0 (npm v6.9.0)
 ›   Warning: apollo update available from 2.17.4 to 2.18.1.
++ npx --no-install apollo codegen:generate --target=swift '--includes=./**/*.graphql' --localSchemaFile=schema.json API.swift
 ›   Warning: apollo update available from 2.17.4 to 2.18.1.
Loading Apollo Project [started]
Loading Apollo Project [completed]
Generating query files [started]
Generating query files with 'swift' target [title changed]
Generating query files with 'swift' target [failed]
→ No operations or fragments found to generate code for.
(node:16854) UnhandledPromiseRejectionWarning: Error: No operations or fragments found to generate code for.
    at write (/Users/XXX/MyProject/node_modules/apollo/lib/commands/client/codegen.js:61:39)
    at GraphQLClientProject.project.onDiagnostics [as _onDiagnostics] (/Users/XXX/MyProject/node_modules/apollo/lib/commands/client/codegen.js:84:29)
    at GraphQLClientProject.validate (/Users/XXX/MyProject/node_modules/apollo-language-server/lib/project/client.js:140:18)
    at GraphQLClientProject.validateIfNeeded (/Users/XXX/MyProject/node_modules/apollo-language-server/lib/project/base.js:137:14)
    at Timeout.setTimeout [as _onTimeout] (/Users/XXX/MyProject/node_modules/apollo-language-server/lib/project/base.js:129:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:16854) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:16854) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: No operations or fragments found to generate code for.
    at write (/Users/XXX/MyProject/node_modules/apollo/lib/commands/client/codegen.js:61:39)
    at Task.task (/Users/XXX/MyProject/node_modules/apollo/lib/commands/client/codegen.js:86:46)
Command PhaseScriptExecution failed with a nonzero exit code```

**Comment by aamir-nazir** [comment]
Found a syntax error in Graphql query. However Apollo's error was not descriptive and misleading.
