### ISSUE TITLE
Compile error of generated code with 0.17.0

### ISSUE THREAD

**Issue by cltnschlosser** [apollographql/apollo-ios#838]
<img width="673" alt="image" src="https://user-images.githubusercontent.com/1498529/66954456-0d0ead80-f026-11e9-9d71-171cca45820d.png">

Looks like we lost empty dictionary literals somewhere.

Query. Clearly has `{}` which seems to be the issue trigger.
```
/// query ExplicitPreferenceCompanionQuestions {
  ///   ExplicitPreferences_personalizationQuestions(request: {}) {
  ///     __typename
  ///     companionsQuestion {
  ///       __typename
  ///       selected
  ///     }
  ///   }
  /// }
```

**Comment by cltnschlosser** [comment]
Issue appears to have surfaced sometime between: 2.17.4 - 2.18.3 (codegen versions)

**Comment by cltnschlosser** [comment]
Tried to replace `{}` with `{ field: null }` which is valid, and I get this codegen crash:
```
→ Cannot read property 'kind' of null
TypeError: Cannot read property 'kind' of null
    at expressionFromValue (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:159:23)
    at language_1.SwiftSource.wrap.language_1.SwiftSource.join.Object.entries.map (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:167:87)
    at Array.map (<anonymous>)
    at expressionFromValue (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:166:124)
    at language_1.SwiftSource.wrap.language_1.SwiftSource.join.args.map.arg (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:178:84)
    at Array.map (<anonymous>)
    at Helpers.dictionaryLiteralForFieldArguments (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:177:99)
    at withIndent (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/codeGeneration.js:499:79)
    at GeneratedFile.withIndent (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-core/lib/utilities/CodeGenerator.js:54:9)
    at SwiftAPIGenerator.withIndent (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-core/lib/utilities/CodeGenerator.js:109:26)
```

**Comment by cltnschlosser** [comment]
Sorry @lilyball but all signs point to https://github.com/apollographql/apollo-tooling/commit/f295ac38e7a957114562f34879a256d4194ca06e

**Comment by lilyball** [comment]
Hmm, the only diffs in generated code that that commit should produce are the addition of backticks around identifiers that need escaping. If it's screwing with empty dictionary literals that's extremely surprising.

Can you put together a small reproducible sample (e.g. schema plus query)?

**Comment by cltnschlosser** [comment]
```
query Test {
    employee(request: {}) {
        fullName
    }
}
```
[schema.txt](https://github.com/apollographql/apollo-ios/files/3736558/schema.txt)
Had to rename to `schema.txt` to make github happy

**Comment by cltnschlosser** [comment]
Here is the whole generated API.swift
```
//  This file was automatically generated and should not be edited.

import Apollo
import Foundation

public final class TestQuery: GraphQLQuery {
  /// The raw GraphQL definition of this operation.
  public let operationDefinition =
    """
    query Test {
      employee(request: {}) {
        __typename
        fullName
      }
    }
    """

  public let operationName = "Test"

  public init() {
  }

  public struct Data: GraphQLSelectionSet {
    public static let possibleTypes = ["Query"]

    public static let selections: [GraphQLSelection] = [
      GraphQLField("employee", arguments: ["request": ], type: .object(Employee.selections)),
    ]

    public private(set) var resultMap: ResultMap

    public init(unsafeResultMap: ResultMap) {
      self.resultMap = unsafeResultMap
    }

    public init(employee: Employee? = nil) {
      self.init(unsafeResultMap: ["__typename": "Query", "employee": employee.flatMap { (value: Employee) -> ResultMap in value.resultMap }])
    }

    public var employee: Employee? {
      get {
        return (resultMap["employee"] as? ResultMap).flatMap { Employee(unsafeResultMap: $0) }
      }
      set {
        resultMap.updateValue(newValue?.resultMap, forKey: "employee")
      }
    }

    public struct Employee: GraphQLSelectionSet {
      public static let possibleTypes = ["Employee"]

      public static let selections: [GraphQLSelection] = [
        GraphQLField("__typename", type: .nonNull(.scalar(String.self))),
        GraphQLField("fullName", type: .scalar(String.self)),
      ]

      public private(set) var resultMap: ResultMap

      public init(unsafeResultMap: ResultMap) {
        self.resultMap = unsafeResultMap
      }

      public init(fullName: String? = nil) {
        self.init(unsafeResultMap: ["__typename": "Employee", "fullName": fullName])
      }

      public var __typename: String {
        get {
          return resultMap["__typename"]! as! String
        }
        set {
          resultMap.updateValue(newValue, forKey: "__typename")
        }
      }

      public var fullName: String? {
        get {
          return resultMap["fullName"] as? String
        }
        set {
          resultMap.updateValue(newValue, forKey: "fullName")
        }
      }
    }
  }
}
```

**Comment by lilyball** [comment]
I've reproduced your issue locally and written a test for it. But before I forget, can you file a separate issue for the inability to write `employee(request: { fullName: null })`? AFAIK that should compile.

**Comment by lilyball** [comment]
Looking at this code I'm pretty sure there's also a pre-existing issue with the input object being an empty array.

**Comment by cltnschlosser** [comment]
Okay, yeah. I’ll make a separate issue for the other thing. Thanks for the quick fix!

**Comment by designatednerd** [comment]
Thanks @cltnschlosser and @lilyball for working this out so quick!

**Comment by cltnschlosser** [comment]
@lilyball Here is the issue for the other problem https://github.com/apollographql/apollo-tooling/issues/1592

**Comment by designatednerd** [comment]
(Reopening since the second issue needs to be addressed still)

**Comment by cltnschlosser** [comment]
This can probably stay closed since there is already a ticket that tracks the second issue. Also it can be worked around by not including the parameter that is being set to `null`. Assuming the server isn't dependent on the difference between not set and set to null.

**Comment by designatednerd** [comment]
OK - I'd like to leave it open until I get the updated CLI in here with that fix though.
